name: Build and deploy to AWS S3
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Select Node version
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run linter
        run: npm run lint
      - name: Run style linter
        run: npm run stylelint
      - name: Run type checker
        run: npm run type-check
      - name: Build project
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
      - name: Deploy to S3 bucket
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }} --delete
      - name: Create Cloudfront invalidation for https://wanianki.com
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID}} --path "/*"
      - name: Create Cloudfront invalidation for https://www.wanianki.com
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_WWW_DISTRIBUTION_ID}} --path "/*"
